limit_conn_zone $http_x_real_ip zone=relay_connections:10m;
limit_req_zone $http_x_real_ip zone=relay_handshakes:10m rate=5r/s;

server {
    listen 8080;
    server_tokens off;

    location / {
        limit_conn relay_connections 10;
        limit_req zone=relay_handshakes burst=10 nodelay;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $http_x_real_ip;
        proxy_read_timeout 75s;
        proxy_send_timeout 75s;
        proxy_pass http://relay:7777;
    }
}
